// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Autorization.UserRoleClaimsTransformation.TransformAsync(System.Security.Claims.ClaimsPrincipal)~System.Threading.Tasks.Task{System.Security.Claims.ClaimsPrincipal}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Autorization.UserRoleClaimsTransformation.TransformAsync(System.Security.Claims.ClaimsPrincipal)~System.Threading.Tasks.Task{System.Security.Claims.ClaimsPrincipal}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.BaseController.GetCurrentUserId(Microsoft.AspNetCore.Http.IHttpContextAccessor)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.BaseController.ValidateAndExecuteAsync``1(``0,FluentValidation.IValidator{``0},System.Func{System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}})~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.MessagesController.CreateMessage(System.Int32,WebApp.Infrastructure.Models.MessageModels.MessageCreateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.MessagesController.UpdateMessage(System.Int32,WebApp.Infrastructure.Models.MessageModels.MessageUpdateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.ReportController.SubmitReport(WebApp.Infrastructure.Models.ReportModels.ReportCreateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.TopicsController.AdminUpdateTopic(System.Int32,WebApp.Infrastructure.Models.TopicModels.TopicUpdateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.TopicsController.CreateTopic(WebApp.Infrastructure.Models.TopicModels.TopicCreateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.TopicsController.RateTopic(WebApp.Infrastructure.Models.TopicModels.RateTopicModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.TopicsController.UpdateTopic(System.Int32,WebApp.Infrastructure.Models.TopicModels.TopicUpdateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.UsersController.AdminUpdateUser(System.Int32,WebApp.Infrastructure.Models.UserModels.UserUpdateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Controllers.UsersController.UpdateMyProfile(WebApp.Infrastructure.Models.UserModels.UserUpdateModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Validation.ReportQueryParametersValidator.#ctor")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Validation.TopicQueryParametersValidator.#ctor")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Validation.UserQueryParametersModelValidator.#ctor")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1000:Keywords should be spaced correctly", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Extensions.ApiExtensions.AddApiAuthentication(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Options.IOptions{WebApp.Infrastructure.Auth.JwtOptions})")]
[assembly: SuppressMessage("Security", "CA5404:Do not disable token validation checks", Justification = "<1>", Scope = "member", Target = "~M:WebApp.WebApi.Extensions.ApiExtensions.AddApiAuthentication(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.Extensions.Options.IOptions{WebApp.Infrastructure.Auth.JwtOptions})")]
[assembly: SuppressMessage("Design", "ASP0000:Do not call 'IServiceCollection.BuildServiceProvider' in 'ConfigureServices'", Justification = "<1>")]
